Fix Iterating over Nested Dictionary in For Loop
dotliquid/dotliquid pull request #321
Opened 2018-09-16 14:01 UTC by danielcrabtree

This PR fixes the issues discussed in #320.

2018-12-28 22:44 UTC, danielcrabtree commented
This also now fixes #331

2021-07-06 23:54 UTC, microalps commented
@daviburg This change is breaking, but it is the correct behavior IMHO. The test is changed to reference using item**.Value.**First

2021-07-07 00:39 UTC, microalps commented on src/DotLiquid/Tags/Capture.cs
> +        private static readonly Regex Syntax = R.B(R.Q(@"({0}+)"), Liquid.VariableSignature);
Variable signature includes dotted and bracketed notations. This should be a simple variable name imho. Other regex just include hyphen.

2021-07-08 18:57 UTC, daviburg requested changes

2021-07-08 18:57 UTC, daviburg commented on src/DotLiquid.Tests/Tags/StandardTagTests.cs
> +            Helper.AssertTemplateResult("JaneMike", "{% for item in People %}{{ item.Value.First }}{%endfor%}",
Formatting should be cleaned-up.
If we move parameters to multiple lines, each parameter should start on a new line.

2021-07-08 18:57 UTC, daviburg commented on src/DotLiquid.Tests/Tags/StandardTagTests.cs
> +            Helper.AssertTemplateResult("JaneMike", "{% for item in People %}{{ item.Value.First }}{%endfor%}",
... and use named parameters as we have at least two strings.

2021-07-08 18:57 UTC, daviburg commented on src/DotLiquid.Tests/Tags/StandardTagTests.cs
> +            var dictionary = new Dictionary<string, object> { {
Fix the formatting here also. I assume that there are other use of nested bracketed collection initializers to refer to for consistency.

2021-07-08 18:59 UTC, daviburg commented
> @daviburg This change is breaking, but it is the correct behavior IMHO. The test is changed to reference using item**.Value.**First

Sorry I don't see an existing test been changed in this PR. Could you help me understand the breaking change? What worked before that won't work after this?

2021-07-09 04:35 UTC, microalps commented
> > @daviburg This change is breaking, but it is the correct behavior IMHO. The test is changed to reference using item**.Value.**First
> 
> Sorry I don't see an existing test been changed in this PR. Could you help me understand the breaking change? What worked before that won't work after this?

Yes its hard to see, but if you look carefully at the before and after, the old test for TestForWithNestedDictionary is on line 114 and new one is line 84. The old test remains, but now is applied to a different data set. The difference between these two lines is a ".Value". I missed it several times until I ran it locally.

2021-07-09 17:45 UTC, daviburg commented
> > > @daviburg This change is breaking, but it is the correct behavior IMHO. The test is changed to reference using item**.Value.**First
> > 
> > 
> > Sorry I don't see an existing test been changed in this PR. Could you help me understand the breaking change? What worked before that won't work after this?
> 
> Yes its hard to see, but if you look carefully at the before and after, the old test for TestForWithNestedDictionary is on line 114 and new one is line 84. The old test remains, but now is applied to a different data set. The difference between these two lines is a ".Value". I missed it several times until I ran it locally.

I'm really dense today...
![image](https://user-images.githubusercontent.com/12040431/125116647-e28a4100-e0a1-11eb-8549-ac970a592712.png)

![image](https://user-images.githubusercontent.com/12040431/125116684-f03fc680-e0a1-11eb-9874-b77677d3a163.png)

So before

```
        [Test]
        public void TestForWithNestedDictionary()
        {
            var dictionary = new Dictionary<string, object> { {
            "People", 
            new Dictionary<string, object> {
                    { "ID1", new Dictionary<string, object>{ { "First", "Jane" }, { "Last", "Green" } } },
                    { "ID2", new Dictionary<string, object>{ { "First", "Mike" }, { "Last", "Doe" } } }
                }
            } };

            Helper.AssertTemplateResult("JaneMike", "{% for item in People %}{{ item.First }}{%endfor%}",
                Hash.FromDictionary(dictionary));
        }
```

And after

```
        [Test]
        public void TestForWithNestedDictionary()
        {
            var dictionary = new Dictionary<string, object> { {
            "People", 
            new Dictionary<string, object> {
                    { "ID1", new Dictionary<string, object>{ { "First", "Jane" }, { "Last", "Green" } } },
                    { "ID2", new Dictionary<string, object>{ { "First", "Mike" }, { "Last", "Doe" } } }
                }
            } };

            Helper.AssertTemplateResult("JaneMike", "{% for item in People %}{{ item.Value.First }}{%endfor%}",
                Hash.FromDictionary(dictionary));
        }
```

Ah, ok, going from `{{ item.First }}` to `{{ item.Value.First }}`

Yeah we can't do that as `{{ item.First }}` was explicitly working before.

I didn't understand before that the 'star' characters were to highlight the keyword.

You are not using .First however in the new tests. Can as backward compatibility .First be a shortcut for .Value.First? I'm not really thinking this through, just tossing ideas.

2021-07-11 21:01 UTC, microalps commented
From a performance perspective, I'm not a fan of it and just lets more people continue the same mistake without knowing. Maybe we can cut this code as part of a opt-in flag.

2021-08-22 01:40 UTC, microalps commented
Closing this pull request as the bigger issue was resolved in another PR and the minor issue was incorrectly fixed as mentioned in code review.

2021-08-22 01:40 UTC, closed without merging