Add an interface to create Context with CancellationToken
dotliquid/dotliquid pull request #406
Opened 2020-12-09 09:06 UTC by BoyaWu10

Add an interface to create Context with CancellationToken

2021-01-06 05:00 UTC, BoyaWu10 commented
@daviburg Could you please help to review this PR?

2021-01-06 20:47 UTC, daviburg requested changes

2021-01-06 20:47 UTC, daviburg commented on src/DotLiquid.Tests/ExceptionHandlingTests.cs
> +            var context = new Context(new List<Hash>(), new Hash(), new Hash(), ErrorsOutputMode.Rethrow, 0, source.Token, CultureInfo.InvariantCulture);
I recommend to use named parameters when using constant input values such as 0 or null so it is easier to understand for human readers.

2021-01-06 20:47 UTC, daviburg commented on src/DotLiquid/Context.cs
> +             , CancellationToken cancellationToken
Why not add at the end?

2021-01-06 20:47 UTC, daviburg commented on src/DotLiquid/Context.cs
> +        /// <param name="errorsOutputMode"></param>
Add the XML comment for the new parameter and take the opportunity to fill in the missing comments content for the existing parameters.

2021-01-06 20:47 UTC, daviburg commented on src/DotLiquid/Context.cs
>              SquashInstanceAssignsWithEnvironments();
Avoid code duplication by having one of the two methods call the other one instead.

2021-01-06 20:48 UTC, daviburg commented
Please add a feature work item to the backlog of this and link it to this PR

2021-01-07 03:14 UTC, BoyaWu10 commented
Thanks for the comments. They are fixed in the update. Do we track feature work items in GitHub issues? If so, I've created an issue #407 for this PR.

2021-01-07 05:55 UTC, daviburg commented
> Thanks for the comments. They are fixed in the update. Do we track feature work items in GitHub issues? If so, I've created an issue #407 for this PR.

As we have multiple companies wanting to add various features to DotLiquid lately, we should be a bit more formal with the changes, so yes, we should have a item for each change. I'm not a GitHub expert, but it may well be that all items are 'issues' even feature requests.

2021-01-07 05:59 UTC, daviburg approved these changes

2021-01-07 05:59 UTC, daviburg commented on src/DotLiquid/Context.cs
> +        /// <param name="errorsOutputMode"></param>
The XML param declaration has been added but the comment is still empty. Each comment should be something like:

<param name="errorsOutputMode">Errors output mode</param>

(Feel free to expand the descriptions based on your knowledge of what the parameter does).

2021-01-07 20:14 UTC, merged