[WIP] Strict Liquid Syntax (Part 2)
dotliquid/dotliquid pull request #431
Opened 2021-04-14 03:04 UTC by microalps

- Updated Sort and Capitalize filters to be inline with Reference Library.
- Adds Missing SortNatural filter - useful if you liked the old behavior of Sort
- Adds a way to get back old behaviors of Capitalize

2021-06-07 18:15 UTC, daviburg requested changes

2021-06-07 18:15 UTC, daviburg commented on src/DotLiquid/ExtendedFilters.cs
> +        public static string Titleize(Context context, string input)
Would it be wise to use the existing name from .NET, i.e. ToTitleCase?

2021-06-07 18:15 UTC, daviburg commented on src/DotLiquid/ExtendedFilters.cs
> +            return input.Substring(0, input.Length - trimmed.Length) + char.ToUpper(trimmed[0]) + trimmed.Substring(1);
use named parameters for Substring call as the input parameter type is identical hence the ordering is ambiguous.

2021-06-07 18:15 UTC, daviburg commented on src/DotLiquid/StandardFilters.cs
> +            if (context.SyntaxCompatibilityLevel == SyntaxCompatibility.DotLiquid21)
Consider re-ordering to have oldest version first

2021-06-07 18:15 UTC, daviburg commented on src/DotLiquid/StandardFilters.cs
>          /// <returns></returns>
Update the XML summary description of this filter to more accurately describe the behavior

2021-06-07 18:15 UTC, daviburg commented on src/DotLiquid.Tests/StandardFilterTests.cs
> +        public void TestCapitalizeV21a()
nit: Shopify spec also has as example {{ "title" | capitalize }} and {{ 'capitalize me' | capitalize }}
https://shopify.github.io/liquid/filters/capitalize/
https://shopify.dev/docs/themes/liquid/reference/filters/string-filters#capitalize

2021-06-07 18:15 UTC, daviburg commented on src/DotLiquid/StandardFilters.cs
> +            var ary = enumerableString.ToList();
'ary'? Please use a fully spelled out English word for local variable name.

2021-07-12 16:16 UTC, microalps commented
This is superseded by work in #441 closing for now.

2021-07-12 16:16 UTC, closed without merging