Fix floating numbers parse and respect culture
dotliquid/dotliquid pull request #546
Opened 2024-05-31 07:11 UTC by aeleftheriadis

Fix StandardFilters methods that parses object to string, that fixes floating point numbers with current that has different decimal separator such as comma.

2024-05-31 18:13 UTC, microalps commented
Please create corresponding tests for all the changed methods.

All the best,

Moshe Alfih
microalps web services


On Fri, May 31, 2024 at 3:11 AM Athanasios Eleftheriadis <
***@***.***> wrote:

> Fix StandardFilters methods that parses object to string, that fixes
> floating point numbers with current that has different decimal separator
> such as comma.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/dotliquid/dotliquid/pull/546
> Commit Summary
>
>    - 851c760
>    <https://github.com/dotliquid/dotliquid/pull/546/commits/851c7609d666928f05a1124261ced12d66caf4d4>
>    Fix floating numbers parse and respect culture
>    - 8154ca9
>    <https://github.com/dotliquid/dotliquid/pull/546/commits/8154ca9d20c1396fb77ecaedf4cc7e71863974b7>
>    Merge pull request #1 from
>    aeleftheriadis/aeleftheriadis-tostring-convertostring
>
> File Changes
>
> (1 file <https://github.com/dotliquid/dotliquid/pull/546/files>)
>
>    - *M* src/DotLiquid/StandardFilters.cs
>    <https://github.com/dotliquid/dotliquid/pull/546/files#diff-ed457f6366183673afe68ec920874105e7f0ff783a3a0b59103e0f2861d35667>
>    (14)
>
> Patch Links:
>
>    - https://github.com/dotliquid/dotliquid/pull/546.patch
>    - https://github.com/dotliquid/dotliquid/pull/546.diff
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dotliquid/dotliquid/pull/546>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJPVGHSTVAA4K4AFI76TGTLZFAPCXAVCNFSM6AAAAABISIE3D6VHI2DSMVQWIX3LMV43ASLTON2WKOZSGMZDOMJRHEZDAOI>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2024-06-06 00:05 UTC, microalps requested changes

2024-06-06 00:05 UTC, microalps commented on src/DotLiquid.Tests/StandardFilterTests.cs
> +                template: "{{ 4 | abs }}");
missing culture, what do these tests validate? And no example of fraction in this set of tests.

2024-06-06 00:05 UTC, microalps commented on src/DotLiquid.Tests/StandardFilterTests.cs
> -        public void TestAtMost()
do not remove existing tests unless there is a good justification for that.

2024-06-06 00:05 UTC, microalps commented on src/DotLiquid.Tests/StandardFilterTests.cs
> +                Assert.AreEqual(4, StandardFilters.Ceil(_contextGreekCultureV20, 3.5));
should this also have a test for passing a string as "3,5"?

2024-06-06 07:27 UTC, aeleftheriadis commented
@microalps  I have updated the tests as reviewed

2024-06-10 10:38 UTC, aeleftheriadis reviewed
Reviewed as requested

2024-11-10 01:54 UTC, microalps commented
I will look into this shortly. Sorry I missed this!

2024-11-17 17:01 UTC, microalps requested changes

2024-11-17 17:01 UTC, microalps commented on src/DotLiquid.Tests/StandardFilterTests.cs
> +                Helper.AssertTemplateResult("4", "{{ \"3,5\" | ceil }}");
I would suggest an additional test for thousands separators for both cultures. e.g. 1.234.567,89 should parse for el-GR and 1,234,567.89 for en.

2024-11-17 20:16 UTC, microalps commented
TestFloor_DifferentCultureDecimalSeparator and TestCeil_DifferentCultureDecimalSeparator do not fail without your fixes. There is missing test for intended scenario(s).

2024-11-17 20:27 UTC, microalps commented on src/DotLiquid.Tests/StandardFilterTests.cs
> +                Assert.AreEqual(4, StandardFilters.Ceil(_contextGreekCultureV20, "3,5"));
this is within a using and is the reason the test doesn't fail it seems

2024-11-17 20:36 UTC, microalps requested changes
I think this covers the tests required

2024-11-17 21:09 UTC, microalps requested changes
I think these are the changes needed...

2024-11-24 00:55 UTC, microalps commented
Another note: `Currency` method also calls ToString and presumably is also affected

2024-11-24 16:51 UTC, microalps commented
The more I think about this, it seems that the library incorrectly expects that each individual filter handles the culture setting. In my opinion, it would be more consistent if we simply changed the threads culture in `RenderInternal` if different than the current setting. The only side-effect would be the removal of the proprietary `{% param culture='en-US' %}` or change its behavior to set during initialization and not during render.

2024-11-26 04:55 UTC, microalps commented
Did some more research into this - a fix would probably not be backwards compatible. In testing, I found that `TestEuroCurrencyFromString` has various cultures with decimal separated fractions where those cultures should be comma separated. I assume that the same is true if anyone is relying on passing American numbers as strings with foreign cultures in the context/renderparameters. I'm baffled how to continue here.  I created #555 to track my work thus far on this issue.

2024-12-04 01:41 UTC, microalps commented
Closing this as #555 incorporates this patch and some.

2024-12-04 01:41 UTC, closed without merging

2024-12-04 05:39 UTC, daviburg commented
> Did some more research into this - a fix would probably not be backwards compatible. In testing, I found that `TestEuroCurrencyFromString` has various cultures with decimal separated fractions where those cultures should be comma separated. I assume that the same is true if anyone is relying on passing American numbers as strings with foreign cultures in the context/renderparameters. I'm baffled how to continue here. I created #555 to track my work thus far on this issue.

Correct, backward compatibility would be a big issue for such type of change. We could only do this if we find a way to have it opt-in so current consumers don't suddenly get different outputs upon updating the version with no code change on their end.